server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Rota SPA — redireciona tudo para index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para o backend FastAPI
    location /upload-lote/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        client_max_body_size 20M;
    }

    location /status-lote/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location /lotes/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location /auth/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    location /docs {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }
}
